swagger: '2.0'
info:
  title: 'Bugtracker API'
  description: 'This is the backend for the bugtracker api.'
  version: '1.0.0'
  contact:
    email: 'lavisharma796@gmail.com'
servers:
  - url: '{protocol}://{enviornment}'
    variables:
      protocol:
        enum:
          - http
          - htps
        default: http
      enviornment:
        enum:
          - api.bugtracker.lavisharma.me
          - localhost:4000
        default: api.bugtracker.lavisharma.me
basePath: '/'
tags:
  - name: 'Project'
paths:
  /projects:
    get:
      tags:
        - 'Project'
      summary: 'Get all the projects'
      responses:
        200:
          description: 'Success'
